Mvc2AjaxDemo/Models/ErrorViewModel.cs
using System;

namespace Mvc2AjaxDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mvc2AjaxDemo/Models/Player.cs
using System;

namespace Mvc2AjaxDemo.Models
{
    public class Player
    {
        public Guid Id { get; set; }
        public string Name { get; set; }

        public int JerseyNumber { get; set; }

        public string Position { get; set; }
    }
}

Mvc2AjaxDemo/ViewModels/PlayerListViewModel.cs
using System;
using System.Collections.Generic;

namespace Mvc2AjaxDemo.ViewModels
{
    public class PlayerListViewModel
    {

        public string Team { get; set; }

        public List<PlayerViewModel> Players { get; set; } = new List<PlayerViewModel>();

        public class PlayerViewModel
        {
            public Guid Id { get; set; }
            public string Name { get; set; }
            public int JerseyNumber { get; set; }
            public string Position { get; set; }
            public string ImageUrl { get; set; }

            public int Goals { get; set; }
            public int Assists { get; set; }
        }

        public PlayerViewModel CurrentPlayer { get; set; }
    }

}

Mvc2AjaxDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mvc2AjaxDemo.Models;

namespace Mvc2AjaxDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mvc2AjaxDemo/Controllers/KnockoutController.cs
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Mvc2AjaxDemo.Services;
using Mvc2AjaxDemo.ViewModels;

namespace Mvc2AjaxDemo.Controllers
{
    public class KnockoutController : Controller
    {
        private IPlayerRepository _playerRepository;
        private IWebHostEnvironment _environment;

        public KnockoutController(IPlayerRepository playerRepository, IWebHostEnvironment environment)
        {
            _playerRepository = playerRepository;
            _environment = environment;
        }

        // GET
        public IActionResult Index()
        {
            var model = _playerRepository.GetAll().Select(r => new PlayerListViewModel.PlayerViewModel
            {
                Id = r.Id,
                Assists = 40,
                Goals = 51,
                ImageUrl = Path.Combine(_environment.ContentRootPath, $"/images/{r.Id}.jpg"),
                JerseyNumber = r.JerseyNumber,
                Name = r.Name,
                Position = r.Position

            }).First();
            return View(model);
        }
    }
}

Mvc2AjaxDemo/Controllers/PlayerController.cs
using System;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Mvc2AjaxDemo.Models;
using Mvc2AjaxDemo.Services;
using Mvc2AjaxDemo.ViewModels;

namespace Mvc2AjaxDemo.Controllers
{
    public class PlayerController : Controller
    {
        private readonly IPlayerRepository _playerRepository;
        private readonly IWebHostEnvironment _environment;

        public PlayerController(IPlayerRepository playerRepository, IWebHostEnvironment environment)
        {
            _playerRepository = playerRepository;
            _environment = environment;
        }

        public IActionResult Index(string id)
        {
            var viewModel = new PlayerListViewModel();
            viewModel.Players = _playerRepository.GetAll().Select(PlayerToPlayerViewModel).ToList();
            
            if(!string.IsNullOrEmpty(id))
            {
                viewModel.CurrentPlayer = viewModel.Players.FirstOrDefault(r => r.Id == Guid.Parse(id));
            }
            return View(viewModel);
        }

        public IActionResult JQueryJson()
        {
            var viewModel = new PlayerListViewModel();
            viewModel.Players = _playerRepository.GetAll().Select(PlayerToPlayerViewModel).ToList();
            return View(viewModel);
        }


        public IActionResult GetPlayerJson(Guid id)
        {
            var model = _playerRepository.GetAll().Where(r => r.Id == id).Select(PlayerToPlayerViewModel).SingleOrDefault();
            return Json(model);
        }



        public IActionResult GetPlayerHtml(Guid id)
        {
            var model = _playerRepository.GetAll().Where(r => r.Id == id).Select(PlayerToPlayerViewModel).SingleOrDefault();
            return View(model);
        }



        private PlayerListViewModel.PlayerViewModel PlayerToPlayerViewModel(Player arg)
        {
            return new PlayerListViewModel.PlayerViewModel
            {
                Id = arg.Id,
                JerseyNumber = arg.JerseyNumber,
                Name = arg.Name,
                Position = arg.Position,
                ImageUrl = Path.Combine(_environment.ContentRootPath, $"/images/{arg.Id}.jpg")
            };
        }


    }
}

Mvc2AjaxDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mvc2AjaxDemo/Views/Knockout/Index.cshtml
@model Mvc2AjaxDemo.ViewModels.PlayerListViewModel.PlayerViewModel
@{
    ViewData["Title"] = "Player";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.1/knockout-latest.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/knockout.mapping/2.4.1/knockout.mapping.min.js"></script>

<div class="text-center">
    <h1 class="display-4" data-bind="text: name"></h1>
</div>
<img data-bind="attr:{ src: imageUrl}" />

<div data-bind="visible: goals() > 60">
    <h2>What a scorer!!</h2>
</div>


Mål:
<input type="number" data-bind="value: goals" />
Ass:
<input type="number" data-bind="value: assists" />


<h2>Total points (goals + assists)</h2>
<div data-bind="text: totalPoints()"></div>

<button data-bind="click: addAssist">Add assist</button>
<button data-bind="click: addGoal">Add goal</button>


@section scripts{
    <script>

        var playerVM = function(data) {
            ko.mapping.fromJS(data, {}, this);

            this.addAssist = function () {
                var current = parseInt(this.assists());
                current = current + 1;
                this.assists(current);
            }

            this.addGoal = function () {
                var current = parseInt(this.goals());
                current = current + 1;
                this.goals(current);
            }

            this.totalPoints = ko.computed(function () {
                return parseInt(this.goals()) + parseInt(this.assists());
            }, this);

        }


        var model = @Html.Raw(Json.Serialize(Model));
        //var viewModel = ko.mapping.fromJS(model,mapping);
        var viewModel = new playerVM(model);
        ko.applyBindings(viewModel);
    </script>
}

Mvc2AjaxDemo/Views/Player/GetPlayerHtml.cshtml
@model Mvc2AjaxDemo.ViewModels.PlayerListViewModel.PlayerViewModel

@{
    Layout = null;
}

<h2>Current player: @Model.Name</h2>
<img src="@Model.ImageUrl"/>

Mvc2AjaxDemo/Views/Player/Index.cshtml
@model Mvc2AjaxDemo.ViewModels.PlayerListViewModel
@{
    ViewData["Title"] = "Players";
}

<div class="text-center">
    <h1 class="display-4">Players</h1>
</div>

<table class="table">
    <thead>
    <tr>
        <th scope="col">Name</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var p in Model.Players)
    {
        <tr>
            <td>@p.Name</td>
            <td><a href="#" onclick="fetch('@p.Id')" >Set as current</a></td>
        </tr>
    }
    </tbody>
</table>

<div id="currentPlayerPartial"></div>



@section scripts{
    <script>
        function fetch(id) {

//            $("#currentPlayerPartial").load("/player/getplayerhtml?id=" + id);

            $.ajax({url: "/player/getplayerhtml?id=" + id, success: function(result){
                $("#currentPlayerPartial").html(result);
            }});        



            //var xhr = new XMLHttpRequest();
            //xhr.onreadystatechange = function () {
            //    if (this.readyState == 4 && this.status == 200) {
            //        document.getElementById('currentPlayerPartial').innerHTML = this.responseText;
            //    }
            //};
            //xhr.open('get', '/player/getplayerhtml?id=' + id);
            //xhr.send();
        }

    </script>
}

Mvc2AjaxDemo/Views/Player/JQueryJson.cshtml
@model Mvc2AjaxDemo.ViewModels.PlayerListViewModel
@{
    ViewData["Title"] = "Players";
}

<div class="text-center">
    <h1 class="display-4">Players</h1>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model.Players)
        {
            <tr>
                <td>@p.Name</td>
                <td><a href="#" onclick="fetch('@p.Id')">Set as current</a></td>
            </tr>
        }
    </tbody>
</table>

<h2>Current player: <span id="name"></span></h2>
<img id="url" src="" />




@section scripts{
    <script>
        function fetch(id) {

            //            $("#currentPlayerPartial").load("/player/getplayerhtml?id=" + id);

            $.ajax({
                url: "/player/getplayerjson?id=" + id, success: function (result) {
                    console.dir(result);
                    $("#name").html(result.name);
                    $("#url").attr("src", result.imageUrl);
                }
            });



            //var xhr = new XMLHttpRequest();
            //xhr.onreadystatechange = function () {
            //    if (this.readyState == 4 && this.status == 200) {
            //        document.getElementById('currentPlayerPartial').innerHTML = this.responseText;
            //    }
            //};
            //xhr.open('get', '/player/getplayerhtml?id=' + id);
            //xhr.send();
        }

    </script>
}

Mvc2AjaxDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc2AjaxDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc2AjaxDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="JQueryJson">JQuery and JSON</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Knockout" asp-action="Index">Knockout Hockey</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            
            <hr />Här kan man tänka sig att vi har massa "general" content. Som är inhämtade från databas etc etc
            @DateTime.Now.ToString("yyyyMMdd hhmmss")

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Mvc2AjaxDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>